export interface Usuarios {
    idusr:          any,
    codigo:         string,
    despacho?:      string,
    nombre?:        string,
    tipoUsuario?:   string,
    dictamenes?:    string,
    regiones?:      string,
    folios?:        string,
    noFolios?:      string,
    limfolios?:     string,
    telefono?:      string,
    correo?:        string,
    tipoAbogado?:   string,
    idAbogado?:     string,
    selectUsr?:     any,
    ci_fini?:       Date,
    ci_ffin?:       Date,
}